name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - mdbook-i18n-helpers-[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          prefix: "mdbook-i18n-helpers-"
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: "mdbook-gettext,mdbook-i18n-normalize,mdbook-xgettext"
          archive: $tag-$target
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
